spring:
  datasource:
    url: jdbc:mysql://localhost:3307/QLRP
    username: root
    password: Me@05101983
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  social:
    facebook:
      appId: 662685252140725
      appSecret: eaea5565e9322d8a76850f337b84b1dc
  profiles:
    active: all
server:
  servlet:
    context-path: /lecongtien/api

#@ConditionalOnProperty: Tự map key bên application thành đối tượng
#@Value(${tenKey}): lấy giá trị key bên application thành biến
file:
  upload-dir: C:\Users\My PC\Desktop\Java\cinema\cinema\src\main\java\com\lecongtien\cinema\image

redis:
  host: localhost
  port: 6379


